# Generated by Django 3.0.6 on 2020-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('animal_predicted', models.CharField(max_length=30)),
                ('animal_percentage', models.FloatField()),
            ],
        ),
    ]
